name: Spring Petclinic CI Pipeline

on:
  push:
    branches: [ main, prod ]

# OIDC settings
permissions:
  # This is required for requesting the OIDC token
  id-token: write
  # This is required for actions/checkout
  contents: read

env:
  JFROG_PROJECT_KEY: "td"
  MVN_BUILD_NAME: "maven-spring-petclinic"
  DOCKER_BUILD_NAME: "docker-spring-petclinic"
  MVN_REPO_PREFIX: "backend-maven"
  DOCKER_REPO_PREFIX: "backend-docker"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
   
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: https://soleng.jfrog.io 
        with:
          oidc-provider-name: tomokim-github-actions-integration 
          oidc-audience: tomokim-github-actions-integration
    
      - name: Set up JDK ${{matrix.java}}
        uses: actions/setup-java@v4
        with:
          java-version: ${{matrix.java}}
          distribution: 'adopt'
          cache: maven

      - name: Set environment variables based on branch
        run: |
          if [[ "${{ github.ref_name }}" == "prod" ]]; then
            echo "REPO_ENV=prod" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "REPO_ENV=dev" >> $GITHUB_ENV
          else
            echo "REPO_ENV=test" >> $GITHUB_ENV
          fi

      - name: Configure Maven
        run: |
          # Create minimal settings.xml to avoid security issues
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <settings>
            <servers>
              <server>
                <id>soleng.jfrog.io</id>
                <username>${{ secrets.JFROG_USERNAME }}</username>
                <password>${{ secrets.JFROG_API_TOKEN }}</password>
              </server>
            </servers>
          </settings>
          EOF
       
      - name: Check JFrog connectivity
        run: |
          # Ping the server
          jf rt ping
  
      - name: Configure Maven to use Artifactory virtual repository based on branch and run tests, build and deploy
        run: |
          # Configure artifactory repositories based on env
          MVN_VIRTUAL_REPO="${{ env.JFROG_PROJECT_KEY }}-${{ env.MVN_REPO_PREFIX }}-${{ env.REPO_ENV }}-virtual"
          MVN_LOCAL_REPO="${{ env.JFROG_PROJECT_KEY }}-${{ env.MVN_REPO_PREFIX }}-${{ env.REPO_ENV }}-local"
          MVN_REMOTE_REPO="${{ env.JFROG_PROJECT_KEY }}-${{ env.MVN_REPO_PREFIX }}-${{ env.REPO_ENV }}-remote"
          echo "Using Virtual Repo: $MVN_VIRTUAL_REPO"

          # Configure Maven to use Artifactory virtual repository based on branch
          jf mvnc \
            --repo-resolve-snapshots $MVN_VIRTUAL_REPO \
            --repo-resolve-releases $MVN_REMOTE_REPO \
            --repo-deploy-snapshots $MVN_LOCAL_REPO \
            --repo-deploy-releases $MVN_LOCAL_REPO
        
          # Run tests, build and deploy
          jf mvn clean deploy \
            --build-name=${{ env.MVN_BUILD_NAME }}-${{ env.REPO_ENV }} \
            --build-number=${{ github.run_number }} \
            --project ${{ env.JFROG_PROJECT_KEY }}

      - name: Build and push Docker image with JFrog CLI
        run: |
          # Configure artifactory repositories based on env
          DOCKER_VIRTUAL_REPO="${{ env.JFROG_PROJECT_KEY }}-${{ env.DOCKER_REPO_PREFIX }}-${{ env.REPO_ENV }}-virtual"
          DOCKER_LOCAL_REPO="${{ env.JFROG_PROJECT_KEY }}-${{ env.DOCKER_REPO_PREFIX }}-${{ env.REPO_ENV }}-local"
          DOCKER_REMOTE_REPO="${{ env.JFROG_PROJECT_KEY }}-${{ env.DOCKER_REPO_PREFIX }}-${{ env.REPO_ENV }}-remote"
          echo "Using Virtual Repo: $DOCKER_VIRTUAL_REPO"

          # Build and push Docker image to local repo
          IMAGE_NAME="${{ secrets.JFROG_URL }}/artifactory/${DOCKER_VIRTUAL_REPO}/spring-petclinic:${{ github.run_number }}"
          jf docker build -t $IMAGE_NAME .
          jf docker push $IMAGE_NAME \
            --build-name=${{ env.DOCKER_BUILD_NAME }}-${{ env.REPO_ENV }} \
            --build-number=${{ github.run_number }} \
            --project=${{ env.JFROG_PROJECT_KEY }}
